changelog:
  exclude:
    authors:
      - pre-commit[bot]
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: New Features
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
